System:
  video_file_path: "../data/Hamlyn/output.mp4"
  reference_file_path: "../data/Hamlyn/f7/heartDepthMap_"

  optimization_algorithm: 1
  # 0: normal
  # 1: Distance Only
  # 2: Normal with only the vertices as reporjection
  verbose: false

Optimizer:
  max_iteration: 10

Image:
  fx: 391.656525
  fy: 426.835144
  cx: 165.964371
  cy: 154.498138

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

Preprocessing:
  brightness_threshold: 40
# first 40, then 70, then 60

Visualization:
 width: 1600
 height: 900
 show_only_optimised_part: false


GT_Mesh:
  OrientNormalsConsistentTangentPlane: 20
  Poisson_depth: 9
  Poisson_width: 0.1
  simplification: 3000


